name = "loan-memo-api"
main = "src/index.js"
compatibility_date = "2024-04-01"
account_id = "c2f951e74f19f16fecdf9e04c2efc4ed"

[[d1_databases]]
binding = "yt_data"
database_name = "yt_data"
database_id = "fbce3881-d0b1-4edd-a31b-47be43345456"
